"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import * as maplibregl from "maplibre-gl";
import type { GeoJSONSource, Map as MapLibreMap } from "maplibre-gl";
import { SANITATION_STYLE } from "@/config/sanitation";
import { editingLinesLengthMeters, uniqueSelectedWays } from "@/lib/geometry-editing";
import { appendSanitationDraftFragment, applySanitationEndpointClick, cancelSanitationEditing, closeSanitationCorridor, INITIAL_SANITATION_UI_STATE, sanitationCtaLabel, sanitationDraftGeometry, sanitationDraftHasChanges, sanitationDraftModeAfterClick, sanitationEndpointFeatures, sanitationEndpointMode, selectSanitationCorridor, startSanitationEditing, type SanitationDraft, type SanitationUiState } from "@/lib/sanitation-editor";
import { buildSanitationFeature, sanitationSegmentsAdjacent, sanitationSegmentsOverlap } from "@/lib/sanitation-geometry";
import type { DrainageGeoJsonCollection } from "@/types/drainage";
import type { OsmCandidateCollection, ValidatedGeometryCollection } from "@/types/official";
import type { SanitationCollection, SanitationFeature, SanitationNetworkType } from "@/types/sanitation";

const WORKER_URL = "/maplibre-gl-worker.mjs";
const empty = { type: "FeatureCollection" as const, features: [] };
const meters = (value: number) => `${value.toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} m`;
const networkLabel = (type: SanitationNetworkType) => type === "water" ? "Água" : "Esgoto";
interface Props { candidates: OsmCandidateCollection; paving: ValidatedGeometryCollection; drainage: DrainageGeoJsonCollection; initialWater: SanitationCollection; initialSewer: SanitationCollection }

export function SanitationReviewMap({ candidates, paving, drainage, initialWater, initialSewer }: Props) {
  const containerRef = useRef<HTMLDivElement>(null); const mapRef = useRef<MapLibreMap | null>(null); const uiRef = useRef<SanitationUiState>(INITIAL_SANITATION_UI_STATE); const draftRef = useRef<SanitationDraft | null>(null); const waterRef = useRef(initialWater); const sewerRef = useRef(initialSewer);
  const uniqueCandidates = useMemo(() => uniqueSelectedWays(candidates.features), [candidates.features]); const candidateCollection = useMemo(() => ({ ...candidates, features: uniqueCandidates }), [candidates, uniqueCandidates]);
  const [ui, setUi] = useState<SanitationUiState>(INITIAL_SANITATION_UI_STATE); const [draft, setDraft] = useState<SanitationDraft | null>(null); const [highlighted, setHighlighted] = useState<SanitationFeature | null>(null); const [water, setWater] = useState(initialWater); const [sewer, setSewer] = useState(initialSewer); const [message, setMessage] = useState<string | null>(null); const [mapReady, setMapReady] = useState(false);
  const selected = useMemo(() => uniqueCandidates.find((item) => item.properties.osmId === ui.selectedCorridorId) ?? null, [ui.selectedCorridorId, uniqueCandidates]); const collections = useMemo(() => ({ water, sewer }), [water, sewer]);
  const currentCoordinates = useMemo(() => draft ? sanitationDraftGeometry(draft) : null, [draft]);
  const selectedData = useMemo(() => selected ? { type: "FeatureCollection" as const, features: [selected] } : empty, [selected]);
  const editingCorridorData = useMemo(() => selected && ui.editingNetwork ? { type: "FeatureCollection" as const, features: [{ ...selected, properties: { ...selected.properties, networkType: ui.editingNetwork } }] } : empty, [selected, ui.editingNetwork]);
  const draftData = useMemo(() => ({ type: "FeatureCollection" as const, features: draft ? [...draft.fragments.map((fragment, index) => ({ type: "Feature" as const, properties: { index }, geometry: { type: "LineString" as const, coordinates: fragment.coordinates } })), ...(currentCoordinates ? [{ type: "Feature" as const, properties: { preview: true }, geometry: { type: "LineString" as const, coordinates: currentCoordinates } }] : [])] : [] }), [currentCoordinates, draft]);
  const endpointData = useMemo(() => sanitationEndpointFeatures(draft), [draft]);
  const segmentsFor = useCallback((type: SanitationNetworkType) => selected ? collections[type].features.filter((feature) => feature.properties.osmWayId === selected.properties.osmId) : [], [collections, selected]);
  const overlap = useMemo(() => { if (!draft) return false; const saved = collections[draft.networkType].features.filter((feature) => feature.properties.osmWayId === draft.candidate.properties.osmId && !draft.fragments.some((fragment) => fragment.id === feature.properties.id)); const lines = [...saved.map((feature) => feature.geometry.coordinates), ...draft.fragments.map((fragment) => fragment.coordinates)]; return lines.some((line, index) => lines.slice(index + 1).some((other) => sanitationSegmentsOverlap(line, other, draft.candidate.geometry.coordinates))); }, [collections, draft]);
  const adjacent = useMemo(() => draft ? draft.fragments.some((fragment, index) => draft.fragments.slice(index + 1).some((other) => sanitationSegmentsAdjacent(fragment.coordinates, other.coordinates, draft.candidate.geometry.coordinates))) : false, [draft]);
  useEffect(() => { uiRef.current = ui; draftRef.current = draft; waterRef.current = water; sewerRef.current = sewer; }, [draft, sewer, ui, water]);

  const discardEditing = useCallback(() => { setDraft(null); setUi((state) => cancelSanitationEditing(state)); setMessage(null); }, []);
  const requestCorridorSelection = useCallback((corridorId: string) => { const transition = selectSanitationCorridor(uiRef.current, corridorId, sanitationDraftHasChanges(draftRef.current)); if (transition.requiresConfirmation && !window.confirm("Você possui um trecho ainda não salvo. Deseja descartá-lo e selecionar outra rua?")) return; setDraft(null); setUi(transition.requiresConfirmation ? { selectedCorridorId: corridorId, editingNetwork: null, draftMode: "idle" } : transition.state); setHighlighted(null); setMessage(null); }, []);
  const closeSelection = useCallback(() => { if (sanitationDraftHasChanges(draftRef.current) && !window.confirm("Você possui um trecho ainda não salvo. Deseja descartá-lo e fechar esta rua?")) return; setDraft(null); setUi(closeSanitationCorridor()); setHighlighted(null); setMessage(null); }, []);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key !== "Escape") return; if (uiRef.current.editingNetwork) discardEditing(); else closeSelection(); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [closeSelection, discardEditing]);

  useEffect(() => {
    if (!containerRef.current || mapRef.current) return; maplibregl.setWorkerUrl(WORKER_URL);
    const map = new maplibregl.Map({ container: containerRef.current, center: [-54.658, -20.474], zoom: 14.6, minZoom: 12, maxZoom: 20, attributionControl: false, style: { version: 8, sources: { osm: { type: "raster", tiles: ["https://tile.openstreetmap.org/{z}/{x}/{y}.png"], tileSize: 256, attribution: "© OpenStreetMap contributors" } }, layers: [{ id: "osm", type: "raster", source: "osm", paint: { "raster-opacity": 0.68 } }] } });
    mapRef.current = map; map.addControl(new maplibregl.NavigationControl({ showCompass: false }), "top-left"); map.addControl(new maplibregl.AttributionControl({ compact: true }), "bottom-left");
    map.on("load", () => {
      map.addSource("paving", { type: "geojson", data: paving }); map.addSource("drainage", { type: "geojson", data: drainage }); map.addSource("candidates", { type: "geojson", data: candidateCollection }); map.addSource("selected-corridor", { type: "geojson", data: empty }); map.addSource("editing-corridor", { type: "geojson", data: empty }); map.addSource("water", { type: "geojson", data: initialWater }); map.addSource("sewer", { type: "geojson", data: initialSewer }); map.addSource("draft", { type: "geojson", data: empty }); map.addSource("endpoints", { type: "geojson", data: empty }); map.addSource("highlighted", { type: "geojson", data: empty });
      map.addLayer({ id: "paving", type: "line", source: "paving", paint: { "line-color": SANITATION_STYLE.contextPaving, "line-width": 3, "line-opacity": 0.42 } }); map.addLayer({ id: "drainage", type: "line", source: "drainage", filter: ["==", ["get", "featureType"], "segment"], paint: { "line-color": SANITATION_STYLE.contextDrainage, "line-width": 2, "line-opacity": 0.45 } }); map.addLayer({ id: "candidates", type: "line", source: "candidates", paint: { "line-color": SANITATION_STYLE.candidate, "line-width": 4, "line-opacity": 0.4, "line-dasharray": [2, 1.5] } }); map.addLayer({ id: "candidate-hit", type: "line", source: "candidates", paint: { "line-color": "#000", "line-width": 20, "line-opacity": 0 } });
      map.addLayer({ id: "selected-corridor", type: "line", source: "selected-corridor", paint: { "line-color": SANITATION_STYLE.selectedCorridor, "line-width": 13, "line-opacity": 0.88 } }); map.addLayer({ id: "water", type: "line", source: "water", paint: { "line-color": SANITATION_STYLE.water, "line-width": 7 } }); map.addLayer({ id: "water-hit", type: "line", source: "water", paint: { "line-color": "#000", "line-width": 16, "line-opacity": 0 } }); map.addLayer({ id: "sewer", type: "line", source: "sewer", paint: { "line-color": SANITATION_STYLE.sewer, "line-width": 7, "line-dasharray": [2, 1.5] } }); map.addLayer({ id: "sewer-hit", type: "line", source: "sewer", paint: { "line-color": "#000", "line-width": 16, "line-opacity": 0 } }); map.addLayer({ id: "editing-corridor", type: "line", source: "editing-corridor", paint: { "line-color": ["match", ["get", "networkType"], "water", SANITATION_STYLE.editingWater, SANITATION_STYLE.editingSewer], "line-width": 6, "line-opacity": 0.75 } }); map.addLayer({ id: "highlighted", type: "line", source: "highlighted", paint: { "line-color": SANITATION_STYLE.active, "line-width": 11 } }); map.addLayer({ id: "draft", type: "line", source: "draft", paint: { "line-color": SANITATION_STYLE.active, "line-width": 9 } }); map.addLayer({ id: "endpoints", type: "circle", source: "endpoints", paint: { "circle-radius": 8, "circle-color": ["match", ["get", "label"], "A", SANITATION_STYLE.water, SANITATION_STYLE.sewer], "circle-stroke-color": "#fff", "circle-stroke-width": 3 } });
      map.on("click", "candidate-hit", (event) => { event.preventDefault(); const endpointMode = sanitationEndpointMode(uiRef.current.draftMode); const activeDraft = draftRef.current; if (endpointMode && activeDraft) { const activeHit = event.features?.find((feature) => feature.properties?.osmId === uiRef.current.selectedCorridorId); if (!activeHit) return; const result = applySanitationEndpointClick(activeDraft, endpointMode, [event.lngLat.lng, event.lngLat.lat], activeDraft.candidate.properties.osmId); if (!result) return; setDraft(result.draft); setUi((state) => ({ ...state, draftMode: sanitationDraftModeAfterClick(result.nextMode) })); setMessage(result.error); return; } const id = event.features?.[0]?.properties?.osmId; if (typeof id === "string") requestCorridorSelection(id); });
      for (const type of ["water", "sewer"] as const) map.on("click", `${type}-hit`, (event) => { event.preventDefault(); if (sanitationEndpointMode(uiRef.current.draftMode)) return; const id = event.features?.[0]?.properties?.id; const feature = (type === "water" ? waterRef.current : sewerRef.current).features.find((item) => item.properties.id === id); if (!feature) return; requestCorridorSelection(feature.properties.osmWayId); setHighlighted(feature); });
      map.on("click", (event) => { if (event.defaultPrevented || uiRef.current.editingNetwork) return; setUi(closeSanitationCorridor()); setHighlighted(null); });
      map.on("mouseenter", "candidate-hit", () => { map.getCanvas().style.cursor = sanitationEndpointMode(uiRef.current.draftMode) ? "crosshair" : "pointer"; }); map.on("mouseleave", "candidate-hit", () => { map.getCanvas().style.cursor = sanitationEndpointMode(uiRef.current.draftMode) ? "not-allowed" : ""; }); setMapReady(true);
    }); return () => { map.remove(); mapRef.current = null; };
  }, [candidateCollection, drainage, initialSewer, initialWater, paving, requestCorridorSelection]);

  useEffect(() => { if (!mapReady || !mapRef.current) return; (mapRef.current.getSource("water") as GeoJSONSource).setData(water); (mapRef.current.getSource("sewer") as GeoJSONSource).setData(sewer); (mapRef.current.getSource("selected-corridor") as GeoJSONSource).setData(selectedData); (mapRef.current.getSource("editing-corridor") as GeoJSONSource).setData(editingCorridorData); (mapRef.current.getSource("draft") as GeoJSONSource).setData(draftData); (mapRef.current.getSource("endpoints") as GeoJSONSource).setData(endpointData as GeoJSON.FeatureCollection); (mapRef.current.getSource("highlighted") as GeoJSONSource).setData(highlighted ?? empty); }, [draftData, editingCorridorData, endpointData, highlighted, mapReady, selectedData, sewer, water]);
  useEffect(() => { if (mapReady && mapRef.current) mapRef.current.getCanvas().style.cursor = sanitationEndpointMode(ui.draftMode) ? "not-allowed" : ""; }, [mapReady, ui.draftMode]);

  const begin = (networkType: SanitationNetworkType) => { if (!selected) return; if (sanitationDraftHasChanges(draft) && !window.confirm("Você possui um trecho ainda não salvo. Deseja descartá-lo e editar outra rede?")) return; setDraft({ networkType, candidate: selected, start: null, end: null, fragments: [] }); setUi((state) => startSanitationEditing(state, networkType)); setHighlighted(null); setMessage(null); };
  const addFragment = () => { if (!draft || !currentCoordinates) return; setDraft(appendSanitationDraftFragment(draft, currentCoordinates)); setUi((state) => ({ ...state, draftMode: "define_start" })); setMessage(null); };
  const useFullWay = () => { if (!draft) return; if (draft.fragments.length && !window.confirm("Substituir os fragmentos em edição pelo way completo?")) return; setDraft({ ...draft, start: null, end: null, pendingIdentity: undefined, fragments: [{ ...draft.pendingIdentity, coordinates: draft.candidate.geometry.coordinates, geometryMode: "full_way" }] }); setUi((state) => ({ ...state, draftMode: "ready" })); };
  const editValidated = (type: SanitationNetworkType, feature: SanitationFeature) => { const candidate = uniqueCandidates.find((item) => item.properties.osmId === feature.properties.osmWayId); if (!candidate) return; requestCorridorSelection(candidate.properties.osmId); setHighlighted(feature); setDraft({ networkType: type, candidate, start: feature.geometry.coordinates[0], end: feature.geometry.coordinates.at(-1)!, fragments: [], pendingIdentity: { coordinates: feature.geometry.coordinates, geometryMode: feature.properties.geometryMode, id: feature.properties.id, segmentIndex: feature.properties.segmentIndex } }); setUi({ selectedCorridorId: candidate.properties.osmId, editingNetwork: type, draftMode: "ready" }); };
  const save = async () => { if (!draft || !draft.fragments.length || overlap) return; const existing = collections[draft.networkType].features.filter((feature) => feature.properties.osmWayId === draft.candidate.properties.osmId); let next = Math.max(0, ...existing.map((feature) => feature.properties.segmentIndex)); const features = draft.fragments.map((fragment) => buildSanitationFeature(draft.networkType, draft.candidate, fragment.coordinates, "validated", fragment.segmentIndex ?? ++next, fragment.geometryMode, fragment.id)); const response = await fetch("/api/dev/sanitation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(features) }); const result = await response.json(); if (!response.ok) return setMessage(result.error); if (draft.networkType === "water") setWater(result); else setSewer(result); setDraft(null); setUi((state) => cancelSanitationEditing(state)); setHighlighted(null); setMessage(`${features.length} segmento(s) salvos.`); };
  const remove = async (type: SanitationNetworkType, id: string) => { const response = await fetch("/api/dev/sanitation", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ networkType: type, id }) }); const result = await response.json(); if (type === "water") setWater(result); else setSewer(result); if (highlighted?.properties.id === id) setHighlighted(null); };
  const corridorCount = (collection: SanitationCollection) => new Set(collection.features.map((feature) => feature.properties.osmWayId)).size; const instruction = ui.draftMode === "define_start" ? "Clique no corredor destacado para definir o início." : ui.draftMode === "define_end" ? "Clique no corredor destacado para definir o fim." : null;

  return <main className="flex min-h-dvh flex-col bg-slate-100 lg:grid lg:h-dvh lg:grid-cols-[minmax(0,68fr)_minmax(400px,32fr)] lg:overflow-hidden"><section className="relative h-[50dvh] min-h-[360px] lg:h-dvh"><div ref={containerRef} className="absolute inset-0 h-full w-full" aria-label="Mapa de validação de água e esgoto" /><div className="absolute left-4 right-4 top-4 z-10 flex justify-between"><div className="rounded-2xl bg-white/95 p-4 shadow"><p className="text-[10px] font-bold uppercase text-green-700">Cadastro validado</p><h1 className="mt-1 text-lg font-extrabold">Água e esgoto — cadastro 2025</h1><p className="mt-1 text-xs text-slate-600">Água: {water.features.length} segmentos / {corridorCount(water)} corredores · Esgoto: {sewer.features.length} segmentos / {corridorCount(sewer)} corredores</p><p className="mt-1 text-[11px] text-slate-500">Águas Guariroba S.A. — cadastro de 2025 · Projeto Executivo — Lote 22 — Prancha 02</p></div><span className="h-fit rounded-full bg-green-700 px-3 py-2 text-xs font-bold text-white">Referência validada</span></div>{instruction && <div className="absolute left-1/2 top-28 z-20 -translate-x-1/2 rounded-full bg-slate-950 px-4 py-2 text-center text-sm font-bold text-white">{instruction}</div>}</section>
    <aside className="overflow-y-auto border-l border-slate-200 bg-white p-5"><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-blue-50 p-3"><span className="text-xs font-bold uppercase text-blue-700">Água</span><strong className="block text-xl">{water.features.length} segmentos</strong><small>{corridorCount(water)} corredores</small></div><div className="rounded-xl bg-amber-50 p-3"><span className="text-xs font-bold uppercase text-amber-800">Esgoto</span><strong className="block text-xl">{sewer.features.length} segmentos</strong><small>{corridorCount(sewer)} corredores</small></div></div><p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-950">Posição de referência. Não representa levantamento cadastral de precisão.</p>{message && <p role="status" className="mt-3 rounded-xl bg-slate-100 p-3 text-sm">{message}</p>}
      {selected ? <section className="mt-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-violet-700">Corredor OSM</p><h2 className="mt-1 text-lg font-extrabold">{selected.properties.osmName}</h2><p className="text-sm text-slate-500">{selected.properties.osmId} · {meters(selected.properties.candidateLengthMeters)}</p></div><button type="button" onClick={closeSelection} aria-label="Fechar corredor selecionado" className="grid min-h-11 min-w-11 place-items-center rounded-full border border-slate-200 text-xl font-bold">×</button></div>{(["water", "sewer"] as const).map((type) => { const segments = segmentsFor(type); return <div key={type} className="mt-4 rounded-xl border border-slate-200 p-3"><h3 className="text-xs font-extrabold uppercase">Rede de {networkLabel(type).toLowerCase()} cadastrada neste corredor</h3>{segments.length ? <ul className="mt-2 space-y-2">{segments.map((feature) => <li key={feature.properties.id} className="flex items-center gap-2 text-sm"><button type="button" onClick={() => setHighlighted(feature)} className="min-w-0 flex-1 text-left font-semibold">✓ Trecho {feature.properties.segmentIndex} · {meters(feature.properties.geometryLengthMeters)}</button><button type="button" onClick={() => editValidated(type, feature)} className="font-bold text-blue-700">Editar</button><button type="button" onClick={() => remove(type, feature.properties.id)} className="font-bold text-rose-700">Remover</button></li>)}</ul> : <p className="mt-2 text-sm text-slate-500">Nenhum segmento.</p>}<button type="button" onClick={() => begin(type)} className="mt-3 min-h-10 w-full rounded-lg font-bold text-white" style={{ backgroundColor: SANITATION_STYLE[type] }}>{sanitationCtaLabel(type, segments.length)}</button></div>; })}</section> : <section className="mt-5 rounded-2xl border border-slate-200 p-5"><h2 className="font-extrabold">Selecione uma rua</h2><p className="mt-2 text-sm leading-relaxed text-slate-600">Clique em um corredor no mapa para consultar ou cadastrar rede de água e esgoto.</p></section>}
      {draft && ui.editingNetwork && <section className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4"><h3 className="font-extrabold">Trechos de {networkLabel(ui.editingNetwork).toLowerCase()} nesta via</h3><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => setUi((state) => ({ ...state, draftMode: "define_start" }))} className="min-h-11 rounded-xl bg-blue-600 font-bold text-white">Definir início A</button><button type="button" onClick={() => setUi((state) => ({ ...state, draftMode: "define_end" }))} className="min-h-11 rounded-xl bg-rose-600 font-bold text-white">Definir fim B</button></div><button type="button" disabled={ui.draftMode !== "ready" || !currentCoordinates} onClick={addFragment} className="mt-2 min-h-11 w-full rounded-xl bg-slate-950 font-bold text-white disabled:opacity-40">+ Adicionar trecho</button><button type="button" onClick={useFullWay} className="mt-2 min-h-10 w-full rounded-xl border border-amber-400 font-bold">Usar way completo</button><button type="button" onClick={discardEditing} className="mt-2 min-h-10 w-full rounded-xl border border-slate-300 font-bold">Cancelar edição</button><ul className="mt-4 space-y-2">{draft.fragments.map((fragment, index) => <li key={`${fragment.id ?? "new"}-${index}`} className="rounded-lg bg-white p-3 text-sm"><strong>Trecho {fragment.segmentIndex ?? index + 1}</strong><span className="ml-2 text-slate-500">{meters(editingLinesLengthMeters([fragment.coordinates]))}</span><div className="mt-2 flex gap-3"><button type="button" onClick={() => { setDraft({ ...draft, start: fragment.coordinates[0], end: fragment.coordinates.at(-1)!, pendingIdentity: fragment, fragments: draft.fragments.filter((_, item) => item !== index) }); setUi((state) => ({ ...state, draftMode: "ready" })); }} className="font-bold text-blue-700">Editar</button><button type="button" onClick={() => setDraft({ ...draft, fragments: draft.fragments.filter((_, item) => item !== index) })} className="font-bold text-rose-700">Remover</button></div></li>)}</ul><p className="mt-3 text-sm font-bold">Comprimento cadastrado neste corredor: {meters(draft.fragments.reduce((sum, fragment) => sum + editingLinesLengthMeters([fragment.coordinates]), 0))}</p>{overlap && <p role="alert" className="mt-3 rounded-lg bg-rose-100 p-3 text-sm font-semibold text-rose-950">Este trecho se sobrepõe a outro segmento já cadastrado para esta rede.</p>}{adjacent && !overlap && <p className="mt-3 rounded-lg bg-blue-50 p-3 text-sm text-blue-950">Os segmentos são contínuos. Deseja utilizar um único trecho? Nenhuma união será feita automaticamente.</p>}<button type="button" disabled={!draft.fragments.length || overlap} onClick={save} className="mt-4 min-h-11 w-full rounded-xl bg-green-700 font-bold text-white disabled:bg-slate-300">Validar e salvar {draft.fragments.length} trecho(s)</button></section>}
      <section className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm leading-relaxed"><strong>Fonte:</strong> Águas Guariroba S.A. — cadastro de 2025<br /><strong>Documento:</strong> Projeto Executivo — Lote 22 — Prancha 02<br /><strong>Geometria:</strong> OpenStreetMap como corredor de referência<br /><strong>Precisão:</strong> referencial / não cadastral</section></aside></main>;
}
